# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: appdb
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "53603:53603"
            - "8080:80"